/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controller.AlumnoDao;
import Controller.InscripcionDao;
import Modelo.Materia;
import Controller.MateriaDao;
import Modelo.Alumno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ruben
 */
public class VistaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form Alumno
     */
    /**
     * Creates new form Alumno
     */
    

    private VistaAlumno() {
         initComponents();
       //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBalumno = new javax.swing.JButton();
        jBmateria = new javax.swing.JButton();
        jBinscripcion = new javax.swing.JButton();
        jBmostraralumno = new javax.swing.JButton();
        jBalumnos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBalumno.setText("Materia");
        jBalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalumnoActionPerformed(evt);
            }
        });

        jBmateria.setText("Alumno");
        jBmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmateriaActionPerformed(evt);
            }
        });

        jBinscripcion.setText("inscripcion");
        jBinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscripcionActionPerformed(evt);
            }
        });

        jBmostraralumno.setText("Mos. Alumno");
        jBmostraralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmostraralumnoActionPerformed(evt);
            }
        });

        jBalumnos.setText("Mostrar Alumnos");
        jBalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalumnosActionPerformed(evt);
            }
        });

        jButton1.setText("MOstrar Materias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBalumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBmateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBinscripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jBmostraralumno)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBalumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBalumno)
                    .addComponent(jBmateria))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinscripcion)
                    .addComponent(jBmostraralumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBalumnos)
                    .addComponent(jButton1))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmateriaActionPerformed
      
        
            Alumno alumno=new Alumno(  39137310,"lazaret", "pia", true);
            AlumnoDao aludao= new AlumnoDao();
       
            aludao.agregarAlumno(alumno);
       
        
       
        
    }//GEN-LAST:event_jBmateriaActionPerformed

    private void jBalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalumnoActionPerformed
        Materia materia=new Materia(  "calabaza",1 ,true);
        MateriaDao mate=new MateriaDao();
        mate.agregarMateria(materia);
    }//GEN-LAST:event_jBalumnoActionPerformed

    private void jBinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscripcionActionPerformed
     InscripcionDao inscripcion= new InscripcionDao();
     inscripcion.agregarInscripcion(39137310, "ingles");// TODO add your handling code here:
    }//GEN-LAST:event_jBinscripcionActionPerformed

    private void jBmostraralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmostraralumnoActionPerformed
      Alumno alum=new Alumno();
      AlumnoDao dao= new AlumnoDao();
      alum=dao.mostrarAlumno(39137310);
        System.out.println(alum.toString());
    }//GEN-LAST:event_jBmostraralumnoActionPerformed

    private void jBalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalumnosActionPerformed
      ArrayList<Alumno> alumnos =new ArrayList(); 
      AlumnoDao alum= new AlumnoDao();
      alumnos=alum.mostrarAlumnos();
      for (int i = 0; i < alumnos.size(); i++) {
    Alumno alumno = alumnos.get(i);
  
    System.out.println(alumno.toString());
   
    // ...
}
      
    }//GEN-LAST:event_jBalumnosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Materia> materias =new ArrayList(); 
      MateriaDao mate= new MateriaDao();
      materias=mate.mostrarMaterias();
      for (int i = 0; i < materias.size(); i++) {
    Materia mater = materias.get(i);
  
    System.out.println(mater.toString());
   
    // ...
}  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalumno;
    private javax.swing.JButton jBalumnos;
    private javax.swing.JButton jBinscripcion;
    private javax.swing.JButton jBmateria;
    private javax.swing.JButton jBmostraralumno;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
